### ISSUE TITLE
Extrair o título da canção dos metadados e não da url

### ISSUE THREAD

**Issue by fccoelho** [beatrizmcoimbra/master_thesis#1]
@beatrizmcoimbra no seu notebook de download dos XMLs, você pode puxar o título da canção direamente dos metadados ao invés de utilizar a url como vc está fazendo. Por exemplo:

```python
from music21 import converter

song = converter.parse(url)
title = song.metadata.title
```
Fazendo assim, você tem um título limpo e não `urlencoded`.

**Comment by beatrizmcoimbra** [comment]
arrasou. valeu, Flavio!
